---
# handlers file for redis
- name: start redis
  service:
    name: redis
    state: started 
    enabled: yes

- name: reloaded redis
  service:
    name: redis
    state: reloaded
    enabled: yes

- name: restart redis
  service:
    name: redis
    state: restarted
    enabled: yes
